version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
    working_directory: ~/core-drone-demo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: npm install --quiet
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Run tests
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
